#!/bin/bash

sframe_batch.py -a config_DNN_UL16preVFP/parsedConfigFile_DNN_UL16preVFP_SM.xml
sframe_batch.py -a config_DNN_UL16postVFP/parsedConfigFile_DNN_UL16postVFP_SM.xml
sframe_batch.py -a config_DNN_UL17/parsedConfigFile_DNN_UL17_SM.xml
sframe_batch.py -a config_DNN_UL18/parsedConfigFile_DNN_UL18_SM.xml

sframe_batch.py -a config_DNN_UL16preVFP/parsedConfigFile_DNN_UL16preVFP_Signal.xml
sframe_batch.py -a config_DNN_UL16postVFP/parsedConfigFile_DNN_UL16postVFP_Signal.xml
sframe_batch.py -a config_DNN_UL17/parsedConfigFile_DNN_UL17_Signal.xml
sframe_batch.py -a config_DNN_UL18/parsedConfigFile_DNN_UL18_Signal.xml

sframe_batch.py -a config_DNN_UL16preVFP/parsedConfigFile_DNN_UL16preVFP_DATA.xml
sframe_batch.py -a config_DNN_UL16postVFP/parsedConfigFile_DNN_UL16postVFP_DATA.xml
sframe_batch.py -a config_DNN_UL17/parsedConfigFile_DNN_UL17_DATA.xml
sframe_batch.py -a config_DNN_UL18/parsedConfigFile_DNN_UL18_DATA.xml

